# Generated by Django 4.2.3 on 2023-08-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
        ('users', '0003_alter_fiscal_unidade_alter_xerox_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscal',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal', to='unidades.unidade'),
        ),
        migrations.AlterField(
            model_name='xerox',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xerox', to='unidades.unidade'),
        ),
    ]
