# Generated by Django 4.2.3 on 2023-08-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('colorido', models.BooleanField()),
                ('data_solicitada', models.DateField()),
                ('data_imperssa', models.DateField()),
                ('data_entregue', models.DateField()),
                ('arquivo', models.CharField(max_length=200)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidades.maquina')),
            ],
            options={
                'verbose_name': 'Impressão',
                'verbose_name_plural': 'Impressões',
            },
        ),
    ]
