# Generated by Django 4.2.3 on 2023-08-18 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_impressao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impressao',
            old_name='data_imperssa',
            new_name='data_impressa',
        ),
    ]
