# Generated by Django 4.2.3 on 2023-08-18 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_rename_data_imperssa_impressao_data_impressa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='data_entregue',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='data_impressa',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='maquina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unidades.maquina'),
        ),
    ]
