# Generated by Django 4.2.3 on 2023-08-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_alter_impressao_data_entregue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressao',
            name='data_entregue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impressao',
            name='data_impressa',
            field=models.DateField(blank=True, null=True),
        ),
    ]
